name: Docker Build and Push
on:
  push:
    branches: ['*']
    tags: ['*']
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: unixgeek2/cors-proxy
      - name: Docker Hub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

